version: '3.8'

services:
  client:
    build: ./client
    container_name: client-app
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - server

  server:
    build: ./server
    container_name: server-app
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env   # ระบุเส้นทางไฟล์ .env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
